### ISSUE TITLE
TabNine Exit 0

### ISSUE THREAD

**Issue by Iron-E** [aca/completion-tabnine#3]
# Introduction

Thank you for this plugin! I used tabnine a lot with `coc.nvim`, and this has helped in the transition away from that to the builtin LSP client.

Lately, I am having an issue with tabnine closing before Neovim does. Here's what that looks like:

![cap](https://user-images.githubusercontent.com/36409591/99425973-8e8fd980-28d1-11eb-9da6-404c56143abf.png)

Once tabnine closes, get the error message in the screenshot every time I type.

# Information

* Using the latest Neovim nightly
* Using the latest `completion-nvim` and `completion-tabnine`

**Comment by aca** [comment]
I experienced the same error and fixed it quite a long time ago but forgot to push it. Thx for making the issue!
https://github.com/aca/completion-tabnine/commit/373b556ce383da4cd35eae87c615cc4806af96d8

**Comment by Iron-E** [comment]
I've updated the plugin. If no errors occur over the course of the next day or so I'll close.

Thanks!

**Comment by Iron-E** [comment]
Seems like its working. Thanks again!

**Comment by bresilla** [comment]
I'm still having this problem, even after the update you suggested...

**Comment by bresilla** [comment]
Well, the error was nothing related to your plugin. But for anyone who might have similar problems, i just deleted "$HOME/.config/TabNine/", since it had old API key and settings and it works again :)

**Comment by Iron-E** [comment]
Interesting. Deleting that folder is the first thing I tried, but it didn't fix the issue for me.

Maybe both this plugin's update and the deletion needed to happen?

**Comment by bresilla** [comment]
@Iron-E 
Well, I confirm that i still have the issue (which i though i fixed, but apparently not)...

I still can't figure out is it the plugin or the binary is exiting unexpectedly...
I'll be checking and report if i can find anything here.

**Comment by bresilla** [comment]
There appears to be an issue with the binary itself:

https://github.com/codota/TabNine/issues/300

**Comment by Iron-E** [comment]
The PR makes it seem like the CPU is also playing a factor.

I'll load up `htop` next time I'm at my PC, just to see if I'm getting it too

**Comment by Iron-E** [comment]
@bresilla I booted up my computer just now, lo and behold it TabNine is exiting again. That's so weird… it was working yesterday.

I guess it really did have nothing to do with this plugin ¯\\\_(ツ)\_/¯

**Comment by bresilla** [comment]
@Iron-E 

The problem is directly with the version 3.2.22.

If you go to your plugin directory (where vim-plug or pathogen installed this plugin), you would have a `binaries` directory. There would be the `TabNine` binary and folder called `3.2.22`. 

The executable is symlink (shortcut) to the binary in the `3.2.22` binary. However, when you open VIM/NVIM it automatically downloads the latest Tabnine, thus a folder `3.2.25` (or whatever version is the latest) is created, but the TabNne binary symlink is not changed.

To fix it, i simply updated this link. For me was:
`cd $HOME/.config/plug_vim/completion-tabnine/binaries/` <- plugin directory
`ln -sf 3.2.25/x86_64-unknown-linux-musl/TabNine TabNine_Linux` <- updating the binary symlink

And it works :)

**Comment by Iron-E** [comment]
It's working now. Thanks @bresilla ! The symlink didn't update for me either. @aca can you confirm whether or not your symlink updated?

If none of our symlinks updated then other users' might not either… I took a quick look at `install.sh` but I didn't see anything obvious. It has an `ln -sf` statement at the end so paths should be getting force updated. Of course it could also just be a fluke.

**Comment by alex-popov-tech** [comment]
Hey, darwin tabnine 3.2.28 still seeing TabNine exit 0 :(

**Comment by aca** [comment]
@alex-popov-tech @Iron-E @bresilla 
I think it is issue of tabnine. I might need to add some workaround later.
But for now, just go to plugin directory, change version and execute ```bash install.sh```
```
version=$(curl -sS https://update.tabnine.com/version)
version="3.1.9" # I can confirm that this version works fine.
```

**Comment by Iron-E** [comment]
The issue of exiting 0 is definitely tabnine, but the symlink not updating is probably something from the update script.

Were you able to confirm that the symlink didn't update for you @aca?

If not, it's probably something on our end.

**Comment by aca** [comment]
@Iron-E fixed the script.
Please re-open issue if not fixed.
```
Plug 'aca/completion-tabnine', { 'do': 'version=3.1.9 ./install.sh' }
```

**Comment by alex-popov-tech** [comment]
works now, thanks!

**Comment by Iron-E** [comment]
Thank you!

**Comment by henryoliver** [comment]
The version downgrade fixed the issue for me here:
```
Plug 'aca/completion-tabnine', { 'do': 'version=3.1.9 ./install.sh' }
```
